### PR TITLE
 chayleaf's  [WIP] Touch support (PR 143) 

### PR DESCRIPTION
**Pull request by in0ni**
This is just PR #143 w/ the requested changes.

I would really like this merged, so I decided to take it on as requested changes are simple
- Note I am not familiar w/ the code or C at all.
- I have ran `clang-format` on both files (not lines, entire file)
- Took a guess at the `200` value, and named it as best as I could
- Added requested TODO verbatim

I've tested this PR and works well. As @chayleaf mentioned, on his original PR -- this is not ideal, but after test and usage is actually quite nice! It's more like gestures to scroll, execute, and exit which is perfect. I was already looking at rofi alternatives for touch support, but rather happy I don't have to.

### CODE REVIEW

**Comment by chayleaf** [comment]
hello, you could've just pinged me in the original PR that you'd like to see this merged... the main reason the original PR is a draft is that there are still bugs in it, the review points are easy to address. Also, best practice is to take the original commit (instead of creating a new one) and amend it or add additional commits so authorship information doesn't get lost and git blame still works properly.

**Comment by in0ni** [comment]
The maintainer already did, stating he'd merge with minor changes and no reply for two months.

If you'll take care of this I have no problem removing the PR. Just trying to help and move things along.

-------- Original Message --------

**Comment by chayleaf** [comment]
As I mentioned above, the PR just *doesn't work* in the current state, namely, enter/exit just doesn't work reliably (yes, it works *sometimes*). It doesn't make any sense to merge this until that's fixed.

Silence for two months doesn't mean you shouldn't confirm stuff with others before doing your own thing.

**Comment by in0ni** [comment]
Closing.

@chayleaf, thanks for pointing out that I should have pulled your branch to ensure ownership of original code -- will be careful about this next time. There was no intention to remove authorship from your work. I forked to at least get the code merged.

This is a collaborative space. I was just completing tasks the maintainer requested. I made a bad judgment call: I see a PR, which often means intention to get code merged, with immediate reply from the maintainer that they will merge that is stale for 2 months. Maybe it's also good practice to follow up on your PRs? But we always can't... silence from contributors is not uncommon, we all have busy lives. Often other step in to help, that's the whole point of open source. No one is doing their "own thing", we're all just contributing.

It would be good to have more of a collaborative tone, and thanks for your contribution. cheers.

**Pull request closed without merging**
