### PR TITLE
docs: This branch is not available in any distros

### PR DESCRIPTION
**Pull request by markstos**
Remove those inaccurate docs.

### CODE REVIEW

**Comment by markstos** [comment]
There's progress on an Arch package: https://pastebin.com/Qt2zhcMG

**Comment by norpol** [comment]
Build "instructions" for wayland lbonn/rofi on nixos:

```bash
git clone --recursive https://github.com/lbonn/rofi/
cd rofi
nix-shell -p ninja meson pango pkgconfig cairo xcbutilxrm libxkbcommon librsvg xcbuild xorg.libxcb xcbutilxrm xorg.xcbutilwm xorg.xcbutil xorg.libxcb libstartup_notification check flex bison wayland wayland-protocols xkeyboard_config

meson setup build -Dwayland=enabled
ninja -C build
# update ~/.config/rofi/config and remove "window" if configured
./build/rofi
```

**Comment by tinywrkb** [comment]
AUR package: [rofi-lbonn-wayland-git](https://aur.archlinux.org/packages/rofi-lbonn-wayland-git/)

**Comment by jirutka** [comment]
Alpine Linux package: [rofi-wayland](https://pkgs.alpinelinux.org/packages?name=rofi-wayland&branch=edge).

**Comment by lbonn** [comment]
Since, some packaging efforts are ongoing, let's drop this PR for now. I'll add a section in INSTALL.md or README.md

**Comment by markstos** [comment]
NixOS NUR package; 
 https://github.com/nix-community/nur-combined/blob/master/repos/c0deaddict/pkgs/rofi-wayland/unwrapped.nix 
 ( linked from here: https://nur.nix-community.org/repos/c0deaddict/ )

**Pull request closed without merging**
